.Dd December 2, 2018
.Dt CATGIRL 7
.Os "Causal Agency"
.
.Sh NAME
.Nm catgirl
.Nd IRC client
.
.Sh DESCRIPTION
.Nm
is a curses IRC client
originally intended for
use over anonymous SSH.
.
.Pp
It requires LibreSSL
.Pq Fl ltls
and targets
.Fx ,
Darwin,
.Nx .
.
.Ss Build
On platforms other than
.Fx ,
copy the appropriate file to
.Pa config.mk
and modify as needed.
The default install
.Ev PREFIX
is
.Pa ~/.local .
.
.Pp
.Bd -literal -offset indent
cp $(uname).mk config.mk
make
make install
.Ed
.
.Sh FILES
.Bl -tag -width sandman.m -compact
.It Pa chat.h
shared state and function prototypes
.It Pa chat.c
command line parsing
.It Pa event.c
event loop and process spawning
.It Pa tag.c
tag (channel, query) ID assignment
.It Pa handle.c
incoming command handling
.It Pa input.c
input command handling
.It Pa irc.c
TLS client connection
.It Pa format.c
IRC formatting
.It Pa ui.c
cursed UI
.It Pa term.c
terminal features unsupported by curses
.It Pa edit.c
line editing
.It Pa tab.c
tab-complete
.It Pa url.c
URL detection
.It Pa pls.c
functions which should not have to be written
.It Pa sandman.m
utility for Darwin to signal sleep
.El
.
.Pp
.Bl -tag -width sshd_config -compact
.It Pa sshd_config
anonymous SSH configuration
.It Pa man.sh
.Xr man 1
implementation for chroot
.El
.
.Sh SEE ALSO
.Xr catgirl 1 ,
.Xr sandman 1
.
.Sh BUGS
The UI is currently broken with
.Nx Ap s
curses implementation.
