.Dd December 2, 2018
.Dt SANDMAN 1
.Os
.
.Sh NAME
.Nm sandman
.Nd signal sleep
.
.Sh SYNOPSIS
.Nm
.Ar command ...
.
.Sh DESCRIPTION
.Nm
is a utility for Darwin systems.
It runs the
.Ar command
as a child process
and sends it the
.Dv SIGHUP
signal
when the system goes to sleep.
.
.Sh EXIT STATUS
.Nm
exits with the exit status of the child process.
.
.Sh SEE ALSO
.Xr signal 3
