.Dd July 2, 2019
.Dt SANDMAN 1
.Os
.
.Sh NAME
.Nm sandman
.Nd signal sleep
.
.Sh SYNOPSIS
.Nm
.Ar command ...
.
.Sh DESCRIPTION
.Nm
is a utility for Darwin systems.
It runs the
.Ar command
as a child process.
When the system goes to sleep,
the process is sent
.Dv SIGHUP .
When the system wakes up,
the process is restarted.
.
.Sh EXIT STATUS
.Nm
exits with the exit status of the child process.
.
.Sh SEE ALSO
.Xr signal 3
